# Linear Algebra Handbook


### Some must know Elementary Functions

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. 

In this notebook we are discussing some basic Linear Algebra must know functions which NumPy supported.

- numpy.linalg.eig
- numpy.linalg.det
- numpy.linalg.matrix_rank
- numpy.linalg.solve
- numpy.linalg.inv

In [60]:
import jovian

In [61]:
jovian.commit(project='Zero2Pandas-assign-2-numpy-array-operations',environment=None)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "dudidharam12i/zero2pandas-assign-2-numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations


'https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations'

In [28]:
import numpy as np
#from numpy import linalg as la

In [3]:
# List of functions explained 
function1 = np.linalg.eig
function2 = np.linalg.det
function3 = np.linalg.matrix_rank
function4 = np.linalg.solve
function5 = np.linalg.inv

## Function 1 - numpy.linalg.eig

It computes the eigenvalues and right eigenvectors of square matrix (array)

>Syntax: `linalg.eig(arr)`
>
>It only takes one parameter and that is the array
>
>It returns two arrays, one for eigenvalues and other for the eigenvectors

In [30]:
arr1=np.array([[5,2,0],[2,5,0],[-3,4,6]])
np.linalg.eig(arr1)

(array([6., 7., 3.]),
 array([[ 0.        ,  0.57735027,  0.36650833],
        [ 0.        ,  0.57735027, -0.36650833],
        [ 1.        ,  0.57735027,  0.85518611]]))

We can see that the eigenvalues are real. Moreover, `la.eig` also supports complex input arrays and also returns complex eigenvalues and eigenvectors.

In [31]:
arr2=np.array([[1,1j],[-1j,1]])
np.linalg.eig(arr2)

(array([2.+0.j, 0.+0.j]),
 array([[ 0.        +0.70710678j,  0.70710678+0.j        ],
        [ 0.70710678+0.j        , -0.        +0.70710678j]]))

We can see that the input array was also complex and the returned eigenvalues and eigenvectors are also complex numbers

In [33]:
arr3=np.array([[1,2],[3,4],[1,4]])
np.linalg.eig(arr3)

LinAlgError: Last 2 dimensions of the array must be square

We can see that `la.eig` gives error when we compute eigenvalues for a non-square array. Since, `la.eig` only supports square arrays.

Use this function only when we have square matrices.

In [34]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "dudidharam12i/zero2pandas-assign-2-numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations


'https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations'

## Function 2 - numpy.linalg.det

It computes the determinant of an array(matrix). 
>Syntax: `la.det(a)`
>
>It returns values in float

In [35]:
arr1=np.array([[1,0,0],[0,1,0],[0,0,1]])
np.linalg.det(arr1)

1.0

The determinant of an identity matrix is always 1

In [36]:
arr2=np.array([[1j,-1j],[2,-2j]])
np.linalg.det(arr2)

(2+2j)

It also supports complex numbers as well.

In [37]:
arr3=np.array([[1,2],[1,4],[4,2]])
arr3
np.linalg.det(arr3)

LinAlgError: Last 2 dimensions of the array must be square

We know that calculation of determinant is only supported for square arrays (matrix). So, `la.det` also doesn't supports non-square arrays.

So, det function only supports square matrices

In [38]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "dudidharam12i/zero2pandas-assign-2-numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations


'https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations'

## Function 3 - numpy.linalg.matrix_rank

It returns matrix rank of given array using SVD array.
>Syntax: `linalg.matrix_rank(arr, tol=none, hermitian=False)`
>
>It returns `int` values

In [39]:
marr1=np.array([[1,1,1],[1,1,0],[1,1,1]])
marr1
np.linalg.matrix_rank(marr1)

2

We can see that first row and last row are identical, which results in rank 2

In [40]:
marr2=np.zeros([2,2])
marr2
np.linalg.matrix_rank(marr2)

0

We know that the rank of a zero matrix is always zero

In [41]:
marr3=np.ones([2,3])
marr3
np.linalg.matrix_rank(marr3)

1

`la.matrix_rank` never breaks provided the parameters are right. As rank is defined for non-square arrays also.

So, we can use rank function for any dimension matrix

In [42]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "dudidharam12i/zero2pandas-assign-2-numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations


'https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations'

## Function 4 - numpy.linalg.solve

It solves a system of linear scalar equations.
>Syntax: `linalg.solve(arr1,arr2)`
>
>It breaks if the array arr1 is not square or singular (determinant is zero)

In [44]:
# defining array A (arr1)
arr1=np.array([[1,2,1],[2,3,1],[3,2,3]])
#defining array B (arr2)
arr2=np.array([3,4,9])
np.linalg.solve(arr1,arr2)

array([1., 0., 2.])

We can see that the values of `x=1`, `y=0`, `z=2`, satisfies the given system of linear equations.

In [45]:
arr1=np.array([[1,2],[2,3]])
arr2=np.array([3,4])
np.linalg.solve(arr1,arr2)

array([-1.,  2.])

We have `x=-1`, `y=2`, which clearly satisfies the above system of linear equations

In [46]:
arr1=np.array([[1,1,1],[2,3,4],[1,2,3]])
arr2=np.array([3,4,9])
np.linalg.solve(arr1,arr2)

LinAlgError: Singular matrix

The function `la.solve` is not able to find the solution to the above system of equations as the determinant of array arr1 is zero, which means arr1 is singular.
So we have to avoid singularity of arr1.

We can only solve a system of linear equations if the first matrix is square and non-singular

In [47]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "dudidharam12i/zero2pandas-assign-2-numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations


'https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations'

## Function 5 - numpy.linalg.inv

It returns the inverse of a matrix (The matrix should be square)
>Syntax: `linalg.inv(arr1)`

In [48]:
arr1=np.array([[1,2],[2,1]])
np.linalg.inv(arr1)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

We can see that the inverse is True.

In [49]:
arr2=np.array([[1,0,0],[0,1,0],[0,0,1]])
np.linalg.inv(arr2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

The inverse of an identity matrix is itself

In [50]:
arr3=np.array([[1,1,1],[2,3,4],[1,2,3]])
np.linalg.inv(arr3)

LinAlgError: Singular matrix

We know that the array arr1 is singular which results in this error as inverse of a singular matrix is not possible.

We can only determine inverse if the matrix is non-singular and square

In [51]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "dudidharam12i/zero2pandas-assign-2-numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations


'https://jovian.ai/dudidharam12i/zero2pandas-assign-2-numpy-array-operations'

## Conclusion

We have learnt about some must know elementary linear algebra functions including:
- Eigenvalues and eigenvectors of a matrix
- Determinant of a matrix
- Rank of a matrix
- Solving a system of linear equations
- Inverse of matrix

## Reference Links
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* `numpy.linalg.eig` : https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig
* `numpy.linalg.det` : https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html#numpy.linalg.det
* `numpy.linalg.matrix_rank` : https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html#numpy.linalg.matrix_rank
* `numpy.linalg.solve` : https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve
* `numpy.linalg.inv` : https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>